#!/usr/bin/env bash
#
# ThorVG iOS Build Script (macOS host with Xcode required)
# Cross-compiles ThorVG for:
#   - iOS device         (arm64, iphoneos SDK)
#   - iOS Simulator arm64 (Apple Silicon Macs)
#   - iOS Simulator x86_64 (Intel Macs)
#
# Required: Xcode + Command Line Tools installed.
#
# Optional env knobs:
#   MIN_IOS  -- minimum iOS version target (default 12.0; matches godot-cpp's
#               ios_min_version default)
#   VARIANTS -- space-separated subset of {device sim-arm64 sim-x86_64}
#               (default builds all three)
#
# Outputs static libthorvg.a per variant:
#   thirdparty/thorvg/builddir_ios-arm64/src/libthorvg.a
#   thirdparty/thorvg/builddir_ios-arm64-simulator/src/libthorvg.a
#   thirdparty/thorvg/builddir_ios-x86_64-simulator/src/libthorvg.a

set -e

if [ "$(uname -s)" != "Darwin" ]; then
    echo "ERROR: iOS builds require a macOS host with Xcode."
    echo "       Current host: $(uname -s)"
    exit 1
fi

if ! xcrun --version >/dev/null 2>&1; then
    echo "ERROR: xcrun not found. Install Xcode + Command Line Tools."
    exit 1
fi

MIN_IOS="${MIN_IOS:-12.0}"
VARIANTS="${VARIANTS:-device sim-arm64 sim-x86_64}"

# ---- Resolve toolchain via xcrun ------------------------------------------

IOS_CLANG="$(xcrun --sdk iphoneos -f clang)"
IOS_CLANGXX="$(xcrun --sdk iphoneos -f clang++)"
IOS_AR="$(xcrun --sdk iphoneos -f ar)"
IOS_STRIP="$(xcrun --sdk iphoneos -f strip)"

IPHONEOS_SDK="$(xcrun --sdk iphoneos --show-sdk-path)"
IPHONESIMULATOR_SDK="$(xcrun --sdk iphonesimulator --show-sdk-path)"

# ---- Resolve meson invocation --------------------------------------------

if command -v meson >/dev/null 2>&1; then
    MESON="meson"
elif python3 -m mesonbuild.mesonmain --version >/dev/null 2>&1; then
    MESON="python3 -m mesonbuild.mesonmain"
else
    echo "ERROR: meson not found. Install with: pip3 install --user meson ninja"
    exit 1
fi

if ! command -v ninja >/dev/null 2>&1; then
    echo "ERROR: ninja not found in PATH."
    echo "       Install with: pip3 install --user ninja  (or: brew install ninja)"
    exit 1
fi

# ---- Build per variant ----------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
THORVG_DIR="$SCRIPT_DIR/thirdparty/thorvg"

if [ ! -d "$THORVG_DIR" ]; then
    echo "ERROR: ThorVG submodule not found at $THORVG_DIR"
    echo "       Run: git submodule update --init --recursive"
    exit 1
fi

build_for_variant() {
    local NAME="$1"          # ios-arm64 / ios-arm64-simulator / ios-x86_64-simulator
    local ARCH="$2"          # arm64 / x86_64
    local SDK_PATH="$3"
    local MIN_FLAG="$4"      # -miphoneos-version-min or -mios-simulator-version-min
    local CPU_FAMILY="$5"    # aarch64 / x86_64

    local BUILDDIR_NAME="builddir_$NAME"
    local BUILDDIR="$THORVG_DIR/$BUILDDIR_NAME"
    local CROSSFILE="$BUILDDIR/.cross.ini"

    echo
    echo "=== ThorVG $NAME (min iOS $MIN_IOS, sdk $(basename "$SDK_PATH")) ==="

    rm -rf "$BUILDDIR"
    mkdir -p "$BUILDDIR"

    cat > "$CROSSFILE" <<EOF
# Auto-generated by build_thorvg_ios.sh -- do not edit by hand.
[binaries]
c = '$IOS_CLANG'
cpp = '$IOS_CLANGXX'
ar = '$IOS_AR'
strip = '$IOS_STRIP'
pkg-config = 'false'

[built-in options]
c_args = ['-arch', '$ARCH', '-isysroot', '$SDK_PATH', '$MIN_FLAG=$MIN_IOS', '-fembed-bitcode']
cpp_args = ['-arch', '$ARCH', '-isysroot', '$SDK_PATH', '$MIN_FLAG=$MIN_IOS', '-stdlib=libc++', '-fembed-bitcode']
c_link_args = ['-arch', '$ARCH', '-isysroot', '$SDK_PATH', '$MIN_FLAG=$MIN_IOS']
cpp_link_args = ['-arch', '$ARCH', '-isysroot', '$SDK_PATH', '$MIN_FLAG=$MIN_IOS', '-stdlib=libc++']

[host_machine]
system = 'darwin'
cpu_family = '$CPU_FAMILY'
cpu = '$CPU_FAMILY'
endian = 'little'
EOF

    # -Dthreads=false: matches the Android approach -- ThorVG's threaded task
    # scheduler can have lifecycle issues inside an embedded library on iOS.
    # SIMD stays on, single-threaded raster is still plenty fast for Lottie.
    (cd "$THORVG_DIR" && \
        $MESON setup "$BUILDDIR_NAME" \
            --cross-file "$CROSSFILE" \
            -Dbuildtype=release -Doptimization=3 -Db_ndebug=true \
            -Ddefault_library=static \
            -Dsimd=true -Dthreads=false -Dpartial=true \
            -Dengines=sw -Dloaders=lottie -Dbindings=capi \
            -Dexamples=false -Dtests=false \
            --backend=ninja && \
        $MESON compile -C "$BUILDDIR_NAME")
}

for v in $VARIANTS; do
    case "$v" in
        device)
            build_for_variant ios-arm64 arm64 "$IPHONEOS_SDK" \
                -miphoneos-version-min aarch64
            ;;
        sim-arm64)
            build_for_variant ios-arm64-simulator arm64 "$IPHONESIMULATOR_SDK" \
                -mios-simulator-version-min aarch64
            ;;
        sim-x86_64)
            build_for_variant ios-x86_64-simulator x86_64 "$IPHONESIMULATOR_SDK" \
                -mios-simulator-version-min x86_64
            ;;
        *)
            echo "ERROR: unknown variant '$v'"
            echo "       Valid: device, sim-arm64, sim-x86_64"
            exit 1
            ;;
    esac
done

echo
echo "=== ThorVG iOS build complete ==="
for v in $VARIANTS; do
    case "$v" in
        device)      DIR="$THORVG_DIR/builddir_ios-arm64" ;;
        sim-arm64)   DIR="$THORVG_DIR/builddir_ios-arm64-simulator" ;;
        sim-x86_64)  DIR="$THORVG_DIR/builddir_ios-x86_64-simulator" ;;
    esac
    LIB="$DIR/src/libthorvg.a"
    if [ -f "$LIB" ]; then
        echo "  $v: $LIB ($(du -h "$LIB" | cut -f1))"
    else
        echo "  $v: MISSING"
    fi
done

echo
echo "Next: run ./build_extension_ios.sh to produce the .xcframework."
