#!/usr/bin/env bash
#
# ThorVG Android Build Script (Linux/macOS hosts)
# Cross-compiles ThorVG for Android arm64-v8a + x86_64 using NDK r25+.
#
# Required:
#   ANDROID_NDK_ROOT (or ANDROID_NDK_HOME) -- path to your NDK install
#
# Optional:
#   API     -- Android API level (default 24, the Godot 4.3+ minimum)
#   ABIS    -- space-separated list to build (default "arm64 x86_64")
#
# Outputs:
#   thirdparty/thorvg/builddir_android_arm64/src/libthorvg.a
#   thirdparty/thorvg/builddir_android_x86_64/src/libthorvg.a

set -e

# ---- Resolve NDK ----------------------------------------------------------

if [ -z "$ANDROID_NDK_ROOT" ] && [ -n "$ANDROID_NDK_HOME" ]; then
    ANDROID_NDK_ROOT="$ANDROID_NDK_HOME"
fi

if [ -z "$ANDROID_NDK_ROOT" ]; then
    echo "ERROR: ANDROID_NDK_ROOT (or ANDROID_NDK_HOME) is not set."
    echo
    echo "Point it at your NDK install, for example:"
    echo "  export ANDROID_NDK_ROOT=\$HOME/Android/Sdk/ndk/26.3.11579264"
    exit 1
fi

if [ ! -d "$ANDROID_NDK_ROOT" ]; then
    echo "ERROR: ANDROID_NDK_ROOT='$ANDROID_NDK_ROOT' is not a directory."
    exit 1
fi

# ---- Detect host tag ------------------------------------------------------

case "$(uname -s)" in
    Linux)  HOST_TAG="linux-x86_64" ;;
    Darwin) HOST_TAG="darwin-x86_64" ;;
    *)
        echo "ERROR: unsupported host OS: $(uname -s)"
        echo "       This script targets Linux/macOS hosts. On Windows,"
        echo "       run build_thorvg_android.bat instead."
        exit 1
        ;;
esac

API="${API:-24}"
ABIS="${ABIS:-arm64 x86_64}"

TOOLCHAIN_BIN="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/$HOST_TAG/bin"
if [ ! -d "$TOOLCHAIN_BIN" ]; then
    echo "ERROR: NDK prebuilt toolchain not found at:"
    echo "       $TOOLCHAIN_BIN"
    echo "       (Wrong NDK version or wrong host tag?)"
    exit 1
fi

# ---- Resolve meson invocation --------------------------------------------
# Prefer the `meson` script on PATH; fall back to `python -m mesonbuild.mesonmain`
# which works whenever the meson Python package is importable (e.g. after
# `pip install --user meson` even if ~/.local/bin is not on PATH).

if command -v meson >/dev/null 2>&1; then
    MESON="meson"
elif python3 -m mesonbuild.mesonmain --version >/dev/null 2>&1; then
    MESON="python3 -m mesonbuild.mesonmain"
elif python -m mesonbuild.mesonmain --version >/dev/null 2>&1; then
    MESON="python -m mesonbuild.mesonmain"
else
    echo "ERROR: meson not found."
    echo "       Install with: pip3 install --user meson ninja"
    exit 1
fi
echo "Using meson: $MESON"

if ! command -v ninja >/dev/null 2>&1; then
    echo "ERROR: ninja not found in PATH."
    echo "       Install with: pip3 install --user ninja"
    exit 1
fi

# ---- Build per ABI --------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
THORVG_DIR="$SCRIPT_DIR/thirdparty/thorvg"

if [ ! -d "$THORVG_DIR" ]; then
    echo "ERROR: ThorVG submodule not found at $THORVG_DIR"
    echo "       Run: git submodule update --init --recursive"
    exit 1
fi

build_for_abi() {
    local ABI="$1"
    local TRIPLE="$2"
    local CPU_FAMILY="$3"
    local BUILDDIR_NAME="builddir_android_$ABI"
    local BUILDDIR="$THORVG_DIR/$BUILDDIR_NAME"
    local CROSSFILE="$BUILDDIR/.cross.ini"

    echo
    echo "=== ThorVG $ABI (API $API, host $HOST_TAG) ==="

    rm -rf "$BUILDDIR"
    mkdir -p "$BUILDDIR"

    # Generate the cross-file inside the build directory. It is regenerated
    # on every run, so the build always matches the current NDK env vars.
    cat > "$CROSSFILE" <<EOF
# Auto-generated by build_thorvg_android.sh -- do not edit by hand.
[binaries]
c = '$TOOLCHAIN_BIN/${TRIPLE}-linux-android${API}-clang'
cpp = '$TOOLCHAIN_BIN/${TRIPLE}-linux-android${API}-clang++'
ar = '$TOOLCHAIN_BIN/llvm-ar'
strip = '$TOOLCHAIN_BIN/llvm-strip'
pkg-config = 'false'

[host_machine]
system = 'android'
cpu_family = '$CPU_FAMILY'
cpu = '$CPU_FAMILY'
endian = 'little'
EOF

    (cd "$THORVG_DIR" && \
        $MESON setup "$BUILDDIR_NAME" \
            --cross-file "$CROSSFILE" \
            -Dbuildtype=release -Doptimization=3 -Db_ndebug=true \
            -Ddefault_library=static \
            -Dsimd=true -Dthreads=true -Dpartial=true \
            -Dengines=sw -Dloaders=lottie -Dbindings=capi \
            -Dexamples=false -Dtests=false \
            --backend=ninja && \
        $MESON compile -C "$BUILDDIR_NAME")
}

for abi in $ABIS; do
    case "$abi" in
        arm64)  build_for_abi arm64  aarch64 aarch64 ;;
        x86_64) build_for_abi x86_64 x86_64  x86_64  ;;
        armv7|armv7a|arm)
            build_for_abi armv7 armv7a arm
            ;;
        x86)
            build_for_abi x86 i686 x86
            ;;
        *)
            echo "ERROR: unknown ABI '$abi'"
            exit 1
            ;;
    esac
done

echo
echo "=== ThorVG Android build complete ==="
for abi in $ABIS; do
    LIB="$THORVG_DIR/builddir_android_$abi/src/libthorvg.a"
    if [ -f "$LIB" ]; then
        echo "  $abi: $LIB ($(du -h "$LIB" | cut -f1))"
    else
        echo "  $abi: MISSING"
    fi
done

echo
echo "Next: build the Godot extension per ABI, e.g."
echo "  python3 -m SCons platform=android target=template_release arch=arm64"
echo "  python3 -m SCons platform=android target=template_release arch=x86_64"
